image: k33g/wasm-wasi-tools:0.0.2

tasks:
  - name: initialize
    before: |

      # ------------------------------------
      # wasmer
      # ------------------------------------
      source /home/gitpod/.wasmer/wasmer.sh
      wasmer --version
      # ------------------------------------
      # wasmtime
      # ------------------------------------
      wasmtime --version
      # ------------------------------------
      # wasmedge dependencies
      # ------------------------------------
      source /home/gitpod/.wasmedge/env
      wasmedge --version

    init: |
      echo "🚀 initialize"
      clear
      export DOTNET_ROOT=$HOME/dotnet
      export PATH=$PATH:$HOME/dotnet
      #dotnet workload install wasm-tools
      #dotnet add package Wasi.Sdk --prerelease
      dotnet --version
      # TODO: add it to .bashrc (or check Dockerfile)
      echo "SWIFT_VERSION=\"5.6.0\""  >> $HOME/.bashrc
      echo "export SWIFT_ROOT=\$HOME/swift-wasm-\${SWIFT_VERSION}-RELEASE"  >> $HOME/.bashrc
      echo "export PATH=\$SWIFT_ROOT/usr/bin:\"\${PATH}\""  >> $HOME/.bashrc
      source $HOME/.bashrc
      swiftc --version

vscode:
  extensions:
    - golang.go
    - pkief.material-icon-theme
    - rust-lang.rust
    - bungcip.better-toml
    - aaron-bond.better-comments
    - grain-lang.vscode-grain
    - ms-dotnettools.vscode-dotnet-runtime
